### ISSUE TITLE
Invalid date.timezone value 'EuropeAmsterdam'

### ISSUE THREAD

**Issue by RLinden22** [jgeusebroek/docker-spotweb#25]
Created a container with the latest build, after completing the install, this message is displayed:
"Warning: strftime(): Invalid date.timezone value 'EuropeAmsterdam', we selected the timezone 'UTC' for now. in /var/www/spotweb/lib/SpotTemplateHelper.php on line 1058", in the list of spots.
Tried to start the container with "TZ = Europe\Amsterdam" but error still appears.
![image](https://user-images.githubusercontent.com/57388789/100724474-370a6700-33c3-11eb-8109-565224ab13ae.png)

**Comment by jgeusebroek** [comment]
Hi, it's / not \.

**Comment by RLinden22** [comment]
I get also these warnings when the container is started without TZ variable specified. How to disable this warning?

**Comment by jgeusebroek** [comment]
I cannot replicate this. The default is `Europe/Amsterdam`. Are you sure this is a new spotweb instance?

```
root@faf73eb58cb7:/# php -i | grep timezone
Default timezone => Europe/Amsterdam
date.timezone => Europe/Amsterdam => Europe/Amsterdam
```

**Comment by RLinden22** [comment]
When I run this, I get:
![2020-12-02_09h26_30](https://user-images.githubusercontent.com/57388789/100847819-90849b80-3480-11eb-8f75-57a03fed0ed1.png)
php.ini:
![2020-12-02_09h28_09](https://user-images.githubusercontent.com/57388789/100848002-cfb2ec80-3480-11eb-90cf-c7357c406bfd.png)
Container is created yesterday and is started without TZ variable.

**Comment by jgeusebroek** [comment]
That's very, very strange. Can you run `docker inspect spotweb | grep TZ` and paste the output here?

**Comment by RLinden22** [comment]
![2020-12-02_13h11_10](https://user-images.githubusercontent.com/57388789/100871063-e87eca80-349f-11eb-8d14-12da3c17234e.png)

**Comment by jgeusebroek** [comment]
Ok, and what does `docker exec -ti Spotweb cat /etc/php/7.4/cli/php.ini | grep timezone` output?

This should output:
```
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = Europe/Amsterdam
```

**Comment by RLinden22** [comment]
Here is the output:
![2020-12-03_08h09_33](https://user-images.githubusercontent.com/57388789/100975867-f7688a00-353e-11eb-8166-b73fb1e8545a.png).
Here is also the date output from PHPinfo:
![2020-12-03_08h28_15](https://user-images.githubusercontent.com/57388789/100977664-90000980-3541-11eb-8660-24e499ab7ca7.png)
and the main
![2020-12-03_08h30_10](https://user-images.githubusercontent.com/57388789/100977806-cb023d00-3541-11eb-98f9-26e7c0ed4c08.png)
and the output with the php.ini mentioned in the phpinfo:
![2020-12-03_08h32_42](https://user-images.githubusercontent.com/57388789/100978126-3ea44a00-3542-11eb-8033-bb8f0ff2dccb.png)

**Comment by jgeusebroek** [comment]
I can't think of a reason, I can't replicate this issue. Can you remove the container `docker rm -f Spotweb` and recreate?

**Comment by proddy** [comment]
just to chime in...I'm not seeing the error. I do have a TZ environment variable set to `Europe/Amsterdam` and in docker compose entry looks like:

```
  spotweb:
    image: jgeusebroek/spotweb:latest
    container_name: spotweb
    hostname: spotweb
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${USERDIR}/docker/spotweb:/config
    ports:
      - 8082:80
    restart: always
    environment:
      - SPOTWEB_DB_TYPE=pdo_mysql
      - SPOTWEB_DB_HOST=mariadb
      - SPOTWEB_DB_NAME=spotweb
      - SPOTWEB_DB_USER=spotweb
      - SPOTWEB_DB_PASS=spotweb
      - SPOTWEB_CRON_RETRIEVE=*/30 * * * *
      - SPOTWEB_CRON_CACHE_CHECK=10 */1 * * *
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
```

thanks for the great image Jeroen!
