### ISSUE TITLE
Nice to have: armhf/arm64 builds

### ISSUE THREAD

**Issue by djongepier** [jgeusebroek/docker-spotweb#26]
This is a great image, but I'm missing the ARM builds.
Is it possible to do ARM based builds?

**Comment by jgeusebroek** [comment]
I was thinking about this a while ago. I'm not familiair with cross platform builds and don't have the time at the moment to dive into this.

Pull requests are welcome!

**Comment by djongepier** [comment]
Well I can give it a go, I am not at all informed on how to do it, but I can read a manual.

Let's see how far I can get.

22 dec. 2020 12:08:05 Jeroen Geusebroek <notifications@github.com>:

**Comment by djongepier** [comment]
Hey Jeroen,

I have succeeded in building the image on Raspbian Buster (10) on a Raspberrypi 4 (4GB). This is the armv7(1)/armhf architecture. I needed to install [Libseccomp2](https://packages.debian.org/sid/armhf/libseccomp2/download) on the host to get it to work.
What I can do is do the builds for this architecture for you. On my laptop (when time allows) I can try to get a working build.sh for buildx (experimental feature to build multiplatform on a amd64 host system).

Greetings,

Daniël

**Comment by jgeusebroek** [comment]
Nice! I'm running a Jenkins build environment on amd64. Also dockerhub autobuilds the amd64 image.
Not sure how we would incorporate this. Having different versions (ie. spotweb versions) for both amd64 and arm wouldn't be wise I think.

Thoughts?

**Comment by djongepier** [comment]
My thoughts would be to check out how others incorporate this, and apparently Github actions is a possible solution as well as a solution to make dockerhub build arm too: [Link](https://www.henry.wang/2019/12/05/arm-dockerhub.html)

**Comment by jgeusebroek** [comment]
Sounds good! I don't have time to look into this atm. I've been wanting to check out Github Actions, but I lack time... If you are willing, try to create a build environment. Then I'm willing to implement it of course.

**Comment by djongepier** [comment]
Hey Jeroen,

First you enter the "secrets" for dockerhub in settings > secrets of the repository.
In Actions click on "Setup a workflow yourself" and paste this script in.

The docker Action file should be something like this:
```
name: Spotweb Build

on:
  push:
    branches: master

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            user/app:latest
```
This will result in only one version visible but with three architectures supported.
