### ISSUE TITLE
Unable to connect to database

### ISSUE THREAD

**Issue by mcwieger** [jgeusebroek/docker-spotweb#35]
I'm running the docker image on Synology. I stopped the package and after this, spotweb didn't work anymore.

I re-created the containers with docker-compose:

```
version: "2.1"
services:
  spotweb:
    image: jgeusebroek/spotweb
    container_name: spotweb
    restart: unless-stopped
    environment:
     - PUID=1026
     - PGID=101
     - TZ=Europe/Amsterdam
     - SPOTWEB_DB_TYPE=pdo_mysql
     - SPOTWEB_DB_HOST=spotweb-db
     - SPOTWEB_DB_PORT=3306
     - SPOTWEB_DB_NAME=spotweb
     - SPOTWEB_DB_USER=spotweb
     - SPOTWEB_DB_PASS=spotweb
     - "SPOTWEB_CRON_RETRIEVE=* */480 * * *"
    depends_on:
     - spotweb_db
    ports:
     - 8082:80
    volumes:
     - /volume1/docker/spotweb/config:/config

  spotweb_db:
    image: linuxserver/mariadb
    container_name: spotweb-db
    restart: unless-stopped
    environment:
     - PUID=1026
     - PGID=101
     - MYSQL_ROOT_PASSWORD=mysqlrootpassword
     - TZ=Europe/Amsterdam
     - MYSQL_DATABASE=spotweb
     - MYSQL_USER=spotweb
     - MYSQL_PASSWORD=spotweb
    volumes:
     - /volume1/docker/spotweb/mariadb:/config
    ports:
     - 3306:3306
```

This gives the following error message when trying to connect to spotweb on port 8082:

```
Unable to connect to database:
SQLSTATE[HY000] [2002] Connection timed out

Please make sure your database server is up and running and your connection parameters are set
```

When changing SPOTWEB_DB_HOST to 192.168.2.201 (host ip) or 172.18.0.2 (docker ip) the same message is displayed.

Changing to localhost results in:

```
Unable to connect to database:
SQLSTATE[HY000] [2002] Cannot assign requested address

Please make sure your database server is up and running and your connection parameters are set
```

Changing to 127.0.0.1 results in:

```
Unable to connect to database:
SQLSTATE[HY000] [2002] Connection refused

Please make sure your database server is up and running and your connection parameters are set
```

It doesn't matter if I run the install.php script or change it in dbsettings.inc.php directly.

I tried to connect to mysql in the mariadb container with spotweb@spotweb, that works. So password shouldn't be the issue...

I remember having this issue on initial setup as well. At that time, it seemed it randomly accepted 172.18.0.2 at the 100th try, but I still don't know why or how...

Any ideas?
