### ISSUE TITLE
Unsuccessful install

### ISSUE THREAD

**Issue by lwolfs** [jgeusebroek/docker-spotweb#42]
Hi,

I'm trying to get spotweb running but I encounter a problem I fail to solve...

My docker-compose looks like this:

```
version: '3.3'
services:
    spotweb:
        restart: always
        ports:
            - 9099:80
        container_name: spotweb
        volumes:
            - /data/docker/spotweb:/config
        environment:
            - TZ=Europe/Amsterdam
            - SPOTWEB_DB_TYPE=pdo_mysql
            - SPOTWEB_DB_HOST=my.databaseserver.name
            - SPOTWEB_DB_PORT=8077
            - SPOTWEB_DB_NAME=spotweb
            - SPOTWEB_DB_USER=spotweb
            - SPOTWEB_DB_PASS=my_secret_password
            - SPOTWEB_CRON_RETRIEVE=*/15 * * * *
        image: jgeusebroek/spotweb
```

After deploying this stack (is running),
```
Creating database configuration

rm: cannot remove '/var/www/spotweb/dbsettings.inc.php': No such file or directory

Setting (PHP) time zone to Europe/Amsterdam


sed: can't read /etc/php/7.*/*/php.ini: No such file or directory

 * Starting periodic command scheduler cron

   ...done.
```

 I delete the file /data/docker/spotweb/dbsettings.inc.php as I read in the docs on https://github.com/edv/docker-spotweb

Then I start my browser at my.databaseserver.name:9099/install.php and I get the message:

This site is not reachable
ERR_CONNECTION_REFUSED

My db server is a mariadb instance.
I have tried this now about 10 times, but cannot seem to solve this issue...
I am stuck.

15 minutes later 2 additional lines in the log:

```
Unable to connect to database: No database settings have been entered, please use the 'install.php' wizard to install and configure Spotweb.
If you are upgrading from an earlier version of Spotweb, please consult https://github.com/spotweb/spotweb/wiki/Frequently-asked-questions/ first
```
