### ISSUE TITLE
Unable to get this to work with docker-compose on a Synology nas

### ISSUE THREAD

**Issue by moostmartijn** [jgeusebroek/docker-spotweb#56]
My docker-compose file:
```
  spotweb:
    image: jgeusebroek/spotweb
    container_name: spotweb
    restart: unless-stopped
    environment:
     - PUID=1026
     - GUID=100
     - TZ=Europe/Amsterdam
     - SPOTWEB_DB_TYPE=pdo_mysql
     - SPOTWEB_DB_HOST=spotweb_db
     - SPOTWEB_DB_PORT=3306
     - SPOTWEB_DB_NAME=spotweb
     - SPOTWEB_DB_USER=spotweb
     - SPOTWEB_DB_PASS=spotweb
     - "SPOTWEB_CRON_RETRIEVE=* */2 * * *"
    depends_on:
     - spotweb_db
    ports:
     - 81:80
    volumes:
     - /volume1/apps/spotweb:/config
    network_mode: "service:gluetun"

  spotweb_db:
    image: linuxserver/mariadb
    container_name: spotwebdb
    restart: unless-stopped
    environment:
     - PUID=1026
     - PGID=1000
     - MYSQL_ROOT_PASSWORD=xxxx
     - TZ=Europe/Amsterdam
     - MYSQL_DATABASE=spotweb
     - MYSQL_USER=spotweb
     - MYSQL_PASSWORD=spotweb
    volumes:
     - /volume1/apps/mariadb:/config
    ports:
     - 3306:3306
 ```

In the log:
`rm: cannot remove '/var/www/spotweb/dbsettings.inc.php': No such file or directory`

When restarting the container:
```
Unable to connect to database:
No database settings have been entered, please use the 'install.php' wizard to install and configure Spotweb.
```

<img width="807" alt="Schermafbeelding 2023-03-18 om 11 00 35" src="https://user-images.githubusercontent.com/31592734/226098894-5da24a7a-8e7a-4455-9f1b-bd39208c0297.png">

It seems I'm not the only one when I read the issues. Unfortunately I did not find a solution because I don't have the knowledge to fix it myself...
